id: I9A5B83BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:28:44+00:00'
last_modified: '2022-06-08T06:34:21.797103+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22350
  title: དབུ་མ་འཇུག་པའི་རྩ་བའི་སྦྱོར་ཊིཀ་དང་ས་བཅད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8ABD:
      image_group_id: I1KG22371
      title: ''
      total_pages: 342
      order: 1
      base_file: 8ABD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
