id: P006747
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22350
  title: དབུ་མ་འཇུག་པའི་རྩ་བའི་སྦྱོར་ཊིཀ་དང་ས་བཅད།
  author: ''
  volumes:
    842c1414cfbe4f0691998e6c834f6ec3:
      image_group_id: I1KG22371
      title: ''
      volume_number: 1
      total_pages: 342
      base_file: v001.txt
